### ISSUE TITLE
Fix broken .sync.yml

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-windowsfeature#50]
currently it looks like:

``` yaml

---
Gemfile:
  supports_windows: true
  required:
    ':system_tests':
      - gem: beaker
        version: '2.43.0'
      - gem: beaker-rspec
        version: '5.4.0'
      - gem: winrm
        version: '1.8.1'
      - gem: beaker-puppet_install_helper
spec/acceptance/nodesets/centos-511-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-66-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-72-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-78-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-82-x64.yml:
  unmanaged: true
.travis.yml:
  secure: "hz3gZgI7pMtV6H4m2T1Y418bJ0puwSir2j7oWdkDjB0YjSMwHERvQbbxxfLa47Y/sN2RKo7f5fzMFudriqkw75zyUtnpe4UWITVmQ8DkOQc/G0xb2aCOdenV2CEWZ1fQloL2/n5dYlMgw22iXgb2ARCjhgLYUZG2A9XDKQaQSUk="
```

which results in this Gemfile if you run modulesync:

``` ruby
source ENV['GEM_SOURCE'] || "https://rubygems.org"

def location_for(place, fake_version = nil)
  if place =~ /^(git[:@][^#]*)#(.*)/
    [fake_version, { :git => $1, :branch => $2, :require => false }].compact
  elsif place =~ /^file:\/\/(.*)/
    ['>= 0', { :path => File.expand_path($1), :require => false }]
  else
    [place, { :require => false }]
  end
end

group :system_tests do
  gem 'beaker', '2.43.0',              :require => false
  if beaker_version = ENV['BEAKER_VERSION']
    gem 'beaker', *location_for(beaker_version)
  end
  if beaker_rspec_version = ENV['BEAKER_RSPEC_VERSION']
    gem 'beaker-rspec', *location_for(beaker_rspec_version)
  else
    gem 'beaker-rspec',  :require => false
  end
  gem 'winrm', '1.8.1',                :require => false
  gem 'beaker-puppet_install_helper',  :require => false
end



if facterversion = ENV['FACTER_GEM_VERSION']
gem 'facter', facterversion.to_s, :require => false, :groups => [:test]
else
gem 'facter', :require => false, :groups => [:test]
end

ENV['PUPPET_VERSION'].nil? ? puppetversion = '~> 4.0' : puppetversion = ENV['PUPPET_VERSION'].to_s
gem 'puppet', puppetversion, :require => false, :groups => [:test]

# vim: syntax=ruby
```

the stuff from .sync.yml should be an addition to the Gemfile, not an exclusive list. Our config_defaults.yml already contains beaker/beaker-rspec/beaker-puppet_installhelper, so they aren't needed, only winrm.
